# Generated by Django 5.0.7 on 2024-07-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoLink', models.URLField()),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('boxing', 'Boxing'), ('kicking', 'Kicking'), ('knees', 'Knees'), ('elbows', 'Elbows'), ('clinching', 'Clinching'), ('heavy_bag', 'Heavy Bag'), ('shadowboxing', 'Shadowboxing')], default='boxing', max_length=50)),
            ],
        ),
    ]
