# Generated by Django 5.0.7 on 2024-07-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('Muay Thai', 'Muay Thai'), ('HIIT Training', 'HIIT Training'), ('Shadow Boxing', 'Shadow Boxing'), ('Heavy Bag', 'Heavy Bag'), ('Running', 'Running'), ('Weight Lifting', 'Weight Lifting')], max_length=50)),
                ('duration', models.DurationField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
