# Generated by Django 4.2.14 on 2024-07-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
