# Generated by Django 4.2.14 on 2024-07-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparring', '0002_sparring_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparring',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
