# Generated by Django 4.2.14 on 2024-08-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_category_description_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
